name: Formatting

permissions:
  contents: read

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  editorconfig:
    name: EditorConfig Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check formatting with EditorConfig
        uses: editorconfig-checker/action-editorconfig-checker@51f63319f592f97930c73d9c46184d20bd206393
        with:
          version: v4.0.1

      - name: Run editorconfig-checker
        run: editorconfig-checker
